
project:
  type: website

website:
  title: "Portfolio Risk Attribution"
  navbar:
    left:
      - href: 01-risk-analysis.qmd
        text: Portfolio Analysis

format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    code-fold: true
